dist: trusty
sudo: required
language: php
php:
  - '7.0'
  - '7.1'
  
services:
  - mysql

before_install:  
  - mysql -u root --default-character-set=utf8 < tests/MySQL/create.sql
  
before_script:
  - composer install --prefer-source --no-interaction
  
script:
  - ./vendor/bin/phpunit