<?php
namespace Squid\Base;


interface IMySqlCommand {
	
	/**
	 * Set the connection to use.
	 * @param IMySqlConn $conn Connection to use.
	 */
	public function setConnection(IMySqlConn $conn);
	
	/**
	 * Get the bind parameters.
	 * @return array Array of bind params.
	 */
	public function bindParams();
	
	/**
	 * Generate the query string.
	 * @return string Currently set query.
	 */
	public function assemble();
	
	/**
	 * @todo: Add debug method that will return a string of assembly and json encoded bind params.
	 */
	
	/**
	 * Execute the generated query.
	 * @todo Fix return type to correct type
	 * @return mixed|false Result generated by the query, or false on fail.
	 */
	public function execute();
}