<?php
namespace Squid\MySql\Impl\Cmd;


use Squid\MySql\IMySqlCommand;
use Squid\MySql\Connection\IMySqlConnection;


abstract class AbstractCommand implements IMySqlCommand
{
	/** @var IMySqlConnection Connection to use for execution. */
	private $conn	= null;
	
	
	/**
	 * Get the connection.
	 * @todo Fix return type
	 * @return mixed|null Connection.
	 */
	protected function getConn() {
		return $this->conn;
	}
	
	
	/**
	 * Set the connection to use.
	 * @param \Squid\MySql\Connection\IMySqlConnection $conn
	 */
	public function setConnection(IMySqlConnection $conn) {
		$this->conn = $conn;
	}
	
	/**
	 * Execute the generated query.
	 * @todo Fix return type
	 * @return mixed|null Result generated by the query, or null on fail.
	 */
	public function execute() {
		if (is_null($this->conn)) {
			throw new \Exception("Can't execute query, implicitly created without connection!");
		}
		
		$cmd = $this->assemble();
		$bind = $this->bind();
		
		return $this->conn->execute($cmd, $bind);
	}
}