<?php
namespace Squid\MySql\Cmd;


use \Squid\Base\IMySqlConn;
use \Squid\Base\IMySqlCommand;


abstract class AbstractCommand implements IMySqlCommand {
	
	/** @var IMySqlConn Connection to use for execution. */
	private $conn	= null;
	
	
	/**
	 * Set the connection to use.
	 * @param IMySqlConn $conn
	 */
	public function setConnection(IMySqlConn $conn) {
		$this->conn = $conn;
	}
	
	/**
	 * Execute the generated query.
	 * @todo Fix return type
	 * @return mixed|null Result generated by the query, or null on fail.
	 */
	public function execute() {
		if (is_null($this->conn)) {
			throw new \Exception("Can't execute query, implicitly created without connection!");
		}
		
		$cmd = $this->assemble();
		$bind = $this->bindParams();
		
		return $this->conn->execute($cmd, $bind);
	}
	
	
	/**
	 * Get the connection.
	 * @todo Fix return type
	 * @return mixed|null Connection.
	 */
	protected function getConn() {
		return $this->conn;
	}
}