name: "🚦 Unit Tests"

on: push

jobs:
  run_tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: _squid_test_
          MYSQL_USER: _squid_test_u
          MYSQL_PASSWORD: _squid_test_pass_
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: pdo_mysql

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -u _squid_test_u -p_squid_test_pass_ --silent; then
              echo "MySQL is ready"
              break
            fi
            echo "Waiting for MySQL ($i)..."
            sleep 1
          done

      - name: Install Dependencies
        uses: php-actions/composer@v6

      - name: Run PHPUnit
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: _squid_test_
          DB_USER: _squid_test_u
          DB_PASS: _squid_test_pass_
        run: composer test